export const BROWSER_TOOL_REFERENCE: readonly string[] = [
  "1. open: launch a browser and navigate to a URL. Pass headed=true to show the browser window. Pass cookies=true to reuse local browser cookies. Pass browser='webkit' or browser='firefox' for cross-browser testing — one session at a time, so close the current session first before switching engines. Pass cdp='ws://...' to connect to an existing Chrome instance. Pass locale='fr-FR' or deviceScaleFactor=2 to match the users you are testing for — both are fixed for the life of the browser, so decide before opening.",
  "2. playwright: execute Playwright code in Node.js context. Globals: page (Page), context (BrowserContext), browser (Browser), ref (function: snapshot ref ID → Locator). Use `return` to collect data from the page — the response is JSON: { result: <your value>, resultFile: '<path>' }. The result is also written to a tmp file you can read or grep later. Batch multiple actions AND data collection into a single playwright call. Set snapshotAfter=true to auto-snapshot after DOM-changing actions (response adds snapshot alongside result).",
  "3. screenshot: capture page state. Modes: 'snapshot' (ARIA accessibility tree with element refs — preferred for interaction), 'screenshot' (PNG image), 'annotated' (PNG with numbered labels on interactive elements). Pass fullPage=true for full scrollable content. Pass depth=N on a snapshot to keep only the top N levels: on an unfamiliar or large page, depth=3 maps its regions for a few hundred tokens instead of the ten thousand a full tree costs.",
  "4. console_logs: get browser console messages, including uncaught exceptions and unhandled promise rejections (type 'error', with their stack). Filter by type ('error', 'warning', 'log'). Pass clear=true to reset after reading.",
  "5. network_requests: get captured HTTP requests with automatic issue detection (4xx/5xx failures, transport failures such as CORS, DNS or connection errors reported with the browser's reason, duplicate requests, mixed content). Each entry carries the body it sent, with secret-looking keys redacted. Response bodies are never captured — read them with a page.on('response') listener inside playwright. Filter by method, URL, or resource type.",
  "6. performance_metrics: collect Core Web Vitals (FCP, LCP, CLS, INP), navigation timing (TTFB), Long Animation Frames (LoAF) with script attribution, and resource breakdown.",
  "7. accessibility_audit: run a WCAG accessibility audit using axe-core + IBM Equal Access. Returns violations sorted by severity with CSS selectors, HTML context, and fix guidance.",
  "8. close: close the browser and end the session. Always call this when done — it flushes the session video and screenshots to disk.",
];
